security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    ROLE_ETUDIANT: [ROLE_ETUDIANT]
    ROLE_ENSEIGNANT: [ROLE_ENSEIGNANT]

  encoders:
    App\Entity\User:
      algorithm: bcrypt
      cost: 12
    App\Entity\Enseignant:
      algorithm: bcrypt
      cost: 12
    App\Entity\Admin: plaintext
    App\Entity\Etudiant:
      algorithm: bcrypt
      cost: 12

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    from_database:
      entity:
        class: App\Entity\User
        property: email
    from_Ensg:
      entity:
        class: App\Entity\Enseignant
        property: email
    from_Admin:
      entity:
        class: App\Entity\Admin
        property: email
    from_Etud:
      entity:
        class: App\Entity\Etudiant
        property: email
    all_user:
      chain:
        providers: ['from_Ensg', 'from_database', 'from_Admin', 'from_Etud']


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: true
      provider: all_user
      pattern: ^/
      form_login:
        provider: all_user
        check_path: security_login
        use_forward: false
        always_use_default_target_path: false
        default_target_path: /login_user

      logout:
        path: security_lougout
        target: /login

      #            http_basic: true

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN}
    - { path: ^/enseignant, roles:  ROLE_ENSEIGNANT }
    - { path: ^/etudiant, roles:  ROLE_ETUDIANT }
    - { path: ^/api/login, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
    - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY]  }

